dist: xenial
sudo: required

language: node_js
node_js:
  - lts/*

install:
  - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
  - sudo dpkg -i hugo*.deb

script:
  - hugo version
  - hugo

before_deploy:
  - openssl aes-256-cbc -K $encrypted_df51a33bf88d_key -iv $encrypted_df51a33bf88d_iv -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

deploy:
  provider: script
  skip-cleanup: true
  script: rsync -r --quiet --delete-after ${TRAVIS_BUILD_DIR}/public/* ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}
  on:
    branch: master

env:
  global:
    - PRODUCTION=true
    - HUGO_RELEASE=0.54.0
    - secure: QZTD43W+eCjMwlB/QThYdt51Au8VH0deyuOwdZuo1leV75f4EInDFkIjz4IukjpqfUNxXcpMpamgh0IWVSXD0Hu2pskLSIuuOVx2NLsa8UxYQH+Wtq4nXJP1KSENZx//MuIwy6B4B92EUXocG/WMRzBotGwQDQbXHJsMfSSUV53nNrPiXhSyLrAYPEucinmzINExfhgGW2uja/Wp7Ugap5cU4KT7rW4fuVzN6Typ6OQdX2NWQ/Gj9DTIRE2j1FuEcpiUgB5kCiLd8OhKvOg/uyMFCPKi9xQgwgp29QG4aytPgKsZG4DprXydqKd8a+D/mN7wkWalHVkCg0izZY9/4JebdDtlvlEi7STzbaM1CmLw2aY7rWAS0tzN4RheoD2AmuNRGbE1EDulOJEJAzbTepf6hgJ8jSeAiqhsji0ESMYYzcm/u/pP6kuCMLSM/fvFZiVC2+N13qOKghSfjnxnTRnEZzajQnFmh7dPbEedoQFnqBmBZ7gXNIHRPWOMQARZxWghBiw/kuvCKfbe7Rkct3lcYuCEE4GoHVvKleEPDYRWbFbT3fRyMSz2oc0JJftIL0x5RO6MdC60zhYq9lk/xVeQtFeaMWQCBM/C/Ku+rTe6MXwzJgbujSgGy/XeHOb2SYBbS4IQ8N3ZD5j3w3VG1YX+MNF5Hol8itzu+ybu3s8=
    - secure: FJKVMetsjghQ+APhiCdEnP+lSK/LQO3G5GnV8R7/2hRBgJa6g+5V2FyxmIALbQ9xqAL2rLCHxgRDufPhfjBS12oZbJGlWVmIi3RL9AOGyMkb9vKxpXGAzcVSFuPJkVy6/dW6NrucKP/oRldUbcBVAxfxKx8bAEa07o6HsP9QPjIn2TYk7JSfSYubHLQ+9ZpS4OaMf4E4xHilE6n1GJ8QL4Z+DrRBJZYRck++2SObUT6jn2PefF0HyReTwPWjMeSp6Lgo5jg9EAz+SC32TOqGVuiIsLhitonTfNnGQsbswpzPQryvNEY5VOUu6q+eLHKvVwlA2xwIj8UveIlUgM69WBWsNG9tVJFRUVnG7Rb0pRF1KtDJV61/G80X243p2tNZXPEfDjZhCYshOz99im3croMQb58bpP443MZDQEwG+TKp8flkRF64lAxyNNI7orPeWcYA5pZtrceSw3DAy7/dxY7BvcOyKbXvCt/Aei8Dm7AnC+cdEJFAZF9BhHkwqQu46LMbFGTyjWfhThrpLEy3zZNdsCkxKDS38U2yipeghwemTxYSmkMEQjo7n/LLV99ovO7kzaunhSoSmRTH3yy3TjrtmAG4o/XPMLeJ0tD0inJWhR/2Qt8YQjDg64ntAvhN6U15bRxoO8F/7rlEzTSUaaQdEqSZ189iQorh4z6ee30=
    - secure: PqfSo22HTIIx4RDsrUOCoiAEeXVLu7z9ZZ9DI/rFk5PvAcpQpJb2y0e/pV6taaEG0N1eYcawxh9KzlScYukIuQUCJoajyf3aOqe3H/2G9jaOyY4YQj1SDuAbp+3E15H+yrzxvjVg5hgRg5grrx27TB5rJ1F9gf2q+WgKOrUDK7vv0oQcj8NYmeYFSzRO4TFSerfel//HkNwv6/Vn36Rf79y9RLQKyZkTJZ4FWL2YrI+EieXgxiMSyBceDJ1UFc5wlHVHyVd89DwZpqNmdpKOnUoZto1r72ih5rDCdzBeWKQG/sCvMfz0J76IB1cYrtdKxs8r4sO6zLk+phyLRq3fRC89uLFfyTgvSVXs04bjNayPrAFBh+ScC1WCioRyrehua6Wt98wfRDtdmHkhFKgBvA9q8PLbS8qjR0MuCNCtNw3gQuqR0QIKTkp5Oc0Ydd24npiYENezRQBLVrrMB+eem3XsALepxcD1p+NGtZxt5O26/gmAG51WXUYa9FIPEDre5gipTJUF4NyNze+yGME2L+0gUpn0hOGH9n5JpGdPQK49KEcjTWla+ap+Zf/yWN4K7tnv4zTa42Mkig1ocmVuTYOAAg0RPGsEVwoHGD8nMIjNRzSV95uzX4quJg3/HNap7CYlWkHhB3oYr0mFOxNTehHG975PPunODY+tX3H+p4w=
