dist: xenial
sudo: required

before_install:
  - openssl aes-256-cbc -K $encrypted_df51a33bf88d_key -iv $encrypted_df51a33bf88d_iv -in secrets.enc.tar.enc -out secrets.enc.tar -d
  - tar xvf secrets.enc.tar

install:
  - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_${HUGO_RELEASE}_Linux-64bit.deb"
  - sudo dpkg -i hugo*.deb

script:
  - hugo version
  - hugo

before_deploy:
  - mv ${TRAVIS_BUILD_DIR}/deploy_rsa /tmp/deploy_rsa
  - eval "$(ssh-agent -s)"
  - echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip-cleanup: true
  script: rsync -r --quiet --delete-after ${TRAVIS_BUILD_DIR}/public/* ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}
  on:
    branch: master

env:
  global:
    - PRODUCTION=true
    - HUGO_RELEASE=0.40.1
